version: '3.8'

services:
  web:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: hanz_prod_app
    restart: unless-stopped
    ports:
      - 8080:8000
    networks:
      - hanz-nw
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:dbpassword@db:5432/hanz-db
      - DJANGO_SETTINGS_MODULE=hanz.settings.production
      - ALLOW_HOST=new.hanz.lol

  db:
    image: postgres:15-alpine
    container_name: hanz_prod_postgres_db
    restart: unless-stopped
    networks:
      - hanz-nw
      - db
    volumes:
      - /opt/databases/prod/hanz/postgresql/db:/var/lib/postgresql/db
    environment:
      - POSTGRES_DB=hanz-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=dbpassword
      - PGDATA=/var/lib/postgresql/db
      # Add other PostgreSQL configurations as needed

networks:
  hanz-nw:
    driver: bridge
  db:

