version: '3.8'

services:
  web:
    build:
      context: ../../
      dockerfile: Dockerfile.prod
    container_name: hanz_prod_app
    restart: unless-stopped
    ports:
      - 58181:8000
    networks:
      - hanz-nw
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://user:dbpassword@db:5432/hanz-db
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DEBUG=${DEBUG}
      - ALLOW_HOST=${ALLOW_HOST}
      - SECRET_KEY=${SECRET_KEY}
      - CSRF_TRUSTED_ORIGIN=${CSRF_TRUSTED_ORIGIN}
      - COMPRESS_ENABLED=${COMPRESS_ENABLED}
      - REDIS_URL=redis://redis:6379/1

  db:
    image: postgres:15-alpine
    container_name: hanz_prod_postgres_db
    restart: unless-stopped
    networks:
      - hanz-nw
      - db
    volumes:
      - /opt/databases/prod/hanz-web/postgresql/db:/var/lib/postgresql/db
    environment:
      - POSTGRES_DB=hanz-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=dbpassword
      - PGDATA=/var/lib/postgresql/db
      # Add other PostgreSQL configurations as needed

  redis:
    image: redis:7-bookworm
    container_name: hanz_prod_app_redis
    restart: unless-stopped
    networks:
      - hanz-nw


networks:
  hanz-nw:
    driver: bridge
  db:
