version: '3.8'

services:
  web:
    build:
      context: ../../
      dockerfile: prod.Dockerfile
    container_name: hanz_prod_app
    restart: unless-stopped
    ports:
      - "58181:8000"
    networks:
      - hanz-nw
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://user:dbpassword@db:5432/hanz-db
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DEBUG=${DEBUG}
      - ALLOW_HOST=${ALLOW_HOST}
      - SECRET_KEY=${SECRET_KEY}
      - CSRF_TRUSTED_ORIGIN=${CSRF_TRUSTED_ORIGIN}
      - COMPRESS_ENABLED=${COMPRESS_ENABLED}
      - REDIS_URL=redis://redis:6379/1
      - DBBACKUP_S3_ACCESS_KEY_ID=${DBBACKUP_S3_ACCESS_KEY_ID}
      - DBBACKUP_S3_SECRET_KEY=${DBBACKUP_S3_SECRET_KEY}
      - DBBACKUP_S3_BUCKET_NAME=${DBBACKUP_S3_BUCKET_NAME}
      - DBBACKUP_S3_ENDPOINT_URL=${DBBACKUP_S3_ENDPOINT_URL}
      - DBBACKUP_S3_REGION_NAME=${DBBACKUP_S3_REGION_NAME}
      - MEDIA_S3_ACCESS_KEY_ID=${MEDIA_S3_ACCESS_KEY_ID}
      - MEDIA_S3_SECRET_KEY=${MEDIA_S3_SECRET_KEY}
      - MEDIA_S3_BUCKET_NAME=${MEDIA_S3_BUCKET_NAME}
      - MEDIA_S3_ENDPOINT_URL=${MEDIA_S3_ENDPOINT_URL}
      - MEDIA_S3_REGION_NAME=${MEDIA_S3_REGION_NAME}

  db:
    image: postgres:15-alpine
    container_name: hanz_prod_postgres_db
    restart: unless-stopped
    networks:
      - hanz-nw
      - db
    volumes:
      - /opt/databases/prod/hanz-web/postgresql/db:/var/lib/postgresql/db
    environment:
      - POSTGRES_DB=hanz-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=dbpassword
      - PGDATA=/var/lib/postgresql/db

  redis:
    image: redis:7-bookworm
    container_name: hanz_prod_app_redis
    restart: unless-stopped
    networks:
      - hanz-nw


networks:
  hanz-nw:
    driver: bridge
  db:
