version: '3.8'

services:
  nginx:
    image: nginx:stable
    container_name: hanz_dev_nginx_server
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - web
      - hanz-nw
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/nginx/vhost.dev.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: hanz_app_dev
    restart: unless-stopped
    networks:
      - hanz-nw
      - web
    depends_on:
      - redis
      # - db
    environment:
      # - DATABASE_URL=postgres://user:dbpassword@db:5432/hanz-db
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOW_HOST=${ALLOW_HOST}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - CSRF_TRUSTED_ORIGIN=${CSRF_TRUSTED_ORIGIN}
      - COMPRESS_ENABLED=${COMPRESS_ENABLED}
      - REDIS_URL=redis://redis:6379/1
      - DBBACKUP_S3_ACCESS_KEY_ID=${DBBACKUP_S3_ACCESS_KEY_ID}
      - DBBACKUP_S3_SECRET_KEY=${DBBACKUP_S3_SECRET_KEY}
      - DBBACKUP_S3_BUCKET_NAME=${DBBACKUP_S3_BUCKET_NAME}
      - DBBACKUP_S3_ENDPOINT_URL=${DBBACKUP_S3_ENDPOINT_URL}
      - DBBACKUP_S3_REGION_NAME=${DBBACKUP_S3_REGION_NAME}
      - MEDIA_S3_ACCESS_KEY_ID=${MEDIA_S3_ACCESS_KEY_ID}
      - MEDIA_S3_SECRET_KEY=${MEDIA_S3_SECRET_KEY}
      - MEDIA_S3_BUCKET_NAME=${MEDIA_S3_BUCKET_NAME}
      - MEDIA_S3_ENDPOINT_URL=${MEDIA_S3_ENDPOINT_URL}
      - MEDIA_S3_REGION_NAME=${MEDIA_S3_REGION_NAME}


  # db:
  #   image: postgres:15-bookworm
  #   container_name: hanz_dev_postgres_db
  #   restart: unless-stopped
  #   networks:
  #     - hanz-nw
  #     - db
  #   volumes:
  #     - ./dev_data/postgresql/db:/var/lib/postgresql/db
  #   environment:
  #     - POSTGRES_DB=hanz-db
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=dbpassword
  #     - PGDATA=/var/lib/postgresql/db
      # Add other PostgreSQL configurations as needed


  redis:
    image: redis:7-bookworm
    container_name: hanz_dev_app_redis
    restart: unless-stopped
    networks:
        - hanz-nw

networks:
  hanz-nw:
    driver: bridge
  # db:
  web:
