# fly.toml app configuration file generated for hanz-web on 2023-12-16T05:23:56+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hanz-web"
primary_region = "cdg"
console_command = "/app/manage.py shell"

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[build.args]
  MODE="production"

[deploy]
  release_command = "make migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"
