# Generated by Django 5.0.1 on 2024-01-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_hero_cta_homepage_hero_cta_link_and_more'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_cta',
            field=models.CharField(blank=True, help_text='Homepage Hero Primary Call To Action Text', max_length=30, verbose_name='Hero Primary CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_cta_link',
            field=models.ForeignKey(blank=True, help_text='Homepage Hero Primary CTA Link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero Primary CTA Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_text',
            field=models.CharField(blank=True, help_text='Homepage Primary Hero Text', max_length=100, verbose_name='Hero Primary Text (max 100 chars)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_cta',
            field=models.CharField(blank=True, help_text='Homepage Hero Secondary Call To Action Text', max_length=30, verbose_name='Hero Secondary CTA text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_cta_link',
            field=models.ForeignKey(blank=True, help_text='Homepage Hero Secondary CTA Link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero Secondary CTA Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_text',
            field=models.CharField(blank=True, help_text='Homepage Secondary Hero (paragraph) Text', max_length=255, verbose_name='Hero Secondary Text (paragraph, max 255 chars)'),
        ),
    ]
