# Generated by Django 5.0.7 on 2024-09-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_googletagmanagersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleTagManagerSettings',
        ),
    ]
